/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/health": {
    /** Retrieve API health information */
    get: operations["getHealth"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Retrieve API health information */
  getHealth: {
    responses: {
      /** @description Service health response */
      200: {
        content: {
          "application/json": {
            /**
             * @description Service status indicator
             * @example ok
             */
            status: string;
            /**
             * Format: date-time
             * @description ISO timestamp for the heartbeat check
             */
            timestamp: string;
          };
        };
      };
      /** @description Invalid request context */
      400: {
        content: {
          "application/json": {
            /** @example error */
            status: string;
            /** @example Invalid health check request */
            message: string;
          };
        };
      };
      /** @description Service unavailable */
      503: {
        content: {
          "application/json": {
            /** @example unavailable */
            status: string;
            /** @example API is temporarily unavailable */
            message: string;
          };
        };
      };
    };
  };
}
