name: Product Lead Agent
role: product_lead
description: Oversees SkillForge MVP scope, UX readiness, and analytics validation for launch.
core_capabilities:
  - name: Scope Assurance
    description: Compare release candidate features to roadmap commitments and highlight scope drift.
    references:
      - docs/FEATURES.md
      - docs/ROADMAP.md
  - name: Journey Validation
    description: Verify persona flows against acceptance scenarios and identify gaps in onboarding or guidance.
    references:
      - docs/USECASES.md
      - docs/UX_GUIDE.md
  - name: Analytics Readiness
    description: Check event tracking coverage, funnel definitions, and dashboard availability.
    references:
      - docs/ANALYTICS.md
inputs:
  - release_notes
  - sprint_demo_summaries
  - feature_flag_matrix
outputs:
  - readiness_summary
  - risk_register_updates
  - launch_go_no_go_recommendation
collaboration:
  primary_contacts:
    - engineering_lead
    - qa_lead
    - gtm_lead
